version: "3.4"
services:
    srvpts:
        container_name: dbpt
        image: postgres
        env_file: ./envs/dbpt
        networks:
            - host
        ports:
            - 5432:5432
        volumes:
            - ~/volumes/postgresql:/var/lib/postgresql/data
        restart: always
    srvpga:
        container_name: pgadmin
        image: dpage/pgadmin4
        env_file: ./envs/pga 
        ports:
            - 15432:80
        networks: 
            - host    
    
    srvredis: 
        container_name: redis
        image: redis:6.0
        ports:
            - 6379:6379
        networks: 
            - host
        volumes:
            - ~/volumes/redis:/data   
    web:
        build: .
        container_name: web
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - srvpts
        networks: 
            - host
networks:
    host:
        driver: bridge